# Generated by Django 3.0 on 2020-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='page/')),
                ('title', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('body', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
