# Generated by Django 3.0 on 2020-11-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='page/'),
        ),
    ]
