# Generated by Django 3.0 on 2020-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialists',
            options={'verbose_name_plural': 'Персонал'},
        ),
        migrations.AlterField(
            model_name='specialists',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Должность и звание'),
        ),
        migrations.AlterField(
            model_name='specialists',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя специалиста'),
        ),
    ]
